# Generated by Django 5.1 on 2024-08-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('modules', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('more', models.ManyToManyField(to='api.page')),
            ],
        ),
    ]
