# Generated by Django 5.1 on 2024-08-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wiki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'text'), ('gold', 'gold')], default='text', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='modules',
        ),
        migrations.AlterField(
            model_name='wiki',
            name='more',
            field=models.ManyToManyField(blank=True, null=True, to='api.page'),
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columns', models.ManyToManyField(blank=True, null=True, to='api.column')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'text'), ('block', 'block'), ('image', 'image'), ('table', 'table')], default='text', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('path', models.URLField(blank=True, null=True)),
                ('columns', models.ManyToManyField(blank=True, null=True, to='api.column')),
                ('rows', models.ManyToManyField(blank=True, null=True, to='api.row')),
            ],
        ),
        migrations.AddField(
            model_name='wiki',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, to='api.module'),
        ),
    ]
