# Generated by Django 5.1 on 2024-08-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_column_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='row',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='module',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='wiki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.wiki'),
        ),
        migrations.AddField(
            model_name='module',
            name='columns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
        migrations.AddField(
            model_name='module',
            name='rows',
            field=models.TextField(blank=True, null=True),
        ),
    ]
