# Generated by Django 5.1 on 2024-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_module_columns_remove_row_columns_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='path',
            new_name='root',
        ),
        migrations.AddField(
            model_name='page',
            name='page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
