# Generated by Django 5.1 on 2024-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_path_page_root_page_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background',
            field=models.URLField(blank=True, null=True),
        ),
    ]
