# Generated by Django 5.1 on 2024-08-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_page_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
