# Generated by Django 5.1 on 2024-08-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
