# Generated by Django 5.1 on 2024-08-23 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_page_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='api.page'),
        ),
    ]
