name: Elm Land Deployment (Beta)

on:
  push:
    branches-ignore:
      - "release"
      - "main"
    paths:
      - frontend/**

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Elm Land Deploy
        run: |
          cd frontend/
          elm-land build
          rsync -r --delete-delay dist/ /var/www/seaofthievesbeta.timeofjustice.eu/frontend/
