name: Django Deployment

on: 
  push

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - name: Create virtual environment
        run: |
          cd backend/
          python3.12 -m venv .env
          source .env/bin/activate
          pip3.12 install -r requirements.txt

      - name: Get old database
        run: |
          cd backend/
          rsync -r /var/www/seaofthieves.timeofjustice.eu/backend/db.sqlite3 ./db.sqlite3

      - name: Run Django migrations
        run: |
          cd backend/
          source .env/bin/activate
          python3.12 manage.py migrate

      - name: Collect static files
        run: |
          cd backend/
          source .env/bin/activate
          python3.12 manage.py collectstatic --noinput

      - name: Django Deploy
        run: |
          rsync -r --delete-delay backend/ /var/www/seaofthieves.timeofjustice.eu/backend/

      - name: Restart Django
        run: |
          touch /var/www/seaofthieves.timeofjustice.eu/backend/backend/wsgi.py
