name: Django Deployment

on: push

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - name: Create virtual environment
        run: |
          cd backend/
          python3.12 -m venv .env
          source .env/bin/activate
          pip3.12 install -r requirements.txt

      - name: Django Deploy
        run: |
          rsync -r --delete-delay backend/ /var/www/seaofthieves.timeofjustice.eu/backend/
