name: Elm Land Deployment

on: push

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4

      - name: Elm Land Deploy
        run: |
          cd frontend/
          elm-land build
          rsync -r --delete-delay dist/ /var/www/seaofthieves/
